Update for 04-15-2018 01-50-03

diff --git a/cron-ansible-bash b/cron-ansible-bash
--- a/cron-ansible-bash
+++ b/cron-ansible-bash
@@ -34,18 +34,21 @@ trap 'rm $PIDFILE; exit 1' SIGHUP SIGINT SIGTERM
 
 if [ -f "$PIDFILE" ]; then
     PID=$(cat "${PIDFILE}")
-    if ps -p "$PID" > /dev/null 2>&1; then
+    ps -p "$PID" > /dev/null 2>&1
+    if [ $? -eq 0 ]; then
         echo "Job is already running"
         exit 1
     else
         ## Process not found assume not running
-        if [[ "$(echo $$ > "$PIDFILE")" == 1 ]]; then
+        echo $$ > "$PIDFILE"
+        if [ $? -ne 0 ]; then
             echo "Could not create PID file"
             exit 1
         fi
     fi
 else
-    if [[ "$(echo $$ > "$PIDFILE")" == 1 ]]; then
+    echo $$ > "$PIDFILE"
+    if [ $? -ne 0 ]; then
         echo "Could not create PID file"
         exit 1
     fi
@@ -53,7 +56,7 @@ fi
 
 # First, we will install/update ansible using pip
 sudo -H "${PIP_BIN}" install --upgrade ansible 2>&1 || \
-    echo "For some reason, the installation/upgrade of Ansible failed!"; exit 1
+    { echo "For some reason, the installation/upgrade of Ansible failed!"; exit 1 }
 
 # Next, we pull down any git updates.
 git -C "${DIR}" pull 2>&1;
