Update for 04-15-2018 01-37-58

diff --git a/cron-ansible-bash b/cron-ansible-bash
--- a/cron-ansible-bash
+++ b/cron-ansible-bash
@@ -5,7 +5,7 @@
 # It will attempt to auto-install/update Ansible through pip and then run the
 # playbook.
 
-# Copyright © 2017 JPCDI, JPartain89 and Justin Partain
+# Copyright © 2018 JPCDI, JPartain89 and Justin Partain
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -20,24 +20,43 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+exec 1> >(logger -s -t "$(basename "$0")") 2>&1
+
 export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-LOG_FILE="${DIR}/logs/ansible-update.log"
 
 PIP_BIN="$(command -v pip)"
+ANS_PLAY="$(command -v ansible-playbook)"
+GIT_AUTOPULL="$(command -v git-autopull)"
+PIDFILE="${DIR}/ansible.pid"
 
-trap 'exit 1' SIGHUP SIGINT SIGTERM
+trap 'rm $PIDFILE; exit 1' SIGHUP SIGINT SIGTERM
 
-{
-    echo "################################################################################";
-    echo "###### Starting at $(date '+%m-%d-%Y %H:%M:%S') ########";
-    echo "################################################################################";
+if [ -f "$PIDFILE" ]; then
+    PID=$(cat "${PIDFILE}")
+    if ps -p "$PID" > /dev/null 2>&1; then
+        echo "Job is already running"
+        exit 1
+    else
+        ## Process not found assume not running
+        if echo $$ > "$PIDFILE"; then
+            echo "Could not create PID file"
+            exit 1
+        fi
+    fi
+else
+    if echo $$ > "$PIDFILE"; then
+        echo "Could not create PID file"
+        exit 1
+    fi
+fi
 
-    # First, pull any git updates!
-    git -C "${DIR}" pull 2>&1;
-    ANS_PLAY="$(command -v ansible-playbook)" 2>&1;
-    "${ANS_PLAY}" "${DIR}/main.yml" 2>&1;
+# First, we will install/update ansible using pip
+sudo -H "${PIP_BIN}" install --upgrade ansible 2>&1 || \
+    echo "For some reason, the installation/upgrade of Ansible failed!"; exit 1
 
-    echo "################################################################################";
-    echo "###### Ending at $(date '+%m-%d-%Y %H:%M:%S') ######";
-    echo "################################################################################"; } 2>&1 | sudo tee -a "$LOG_FILE"
+# Next, we pull down any git updates.
+git -C "${DIR}" pull 2>&1;
+cd "${DIR}" && "$GIT_AUTOPULL" &&
+"${ANS_PLAY}" "${DIR}/main.yml" 2>&1 &&
+rm "$PIDFILE"
